###
GET http://localhost:8080/api/courses/

###
GET http://localhost:8080/api/courses/1

###
POST http://localhost:8080/api/courses/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMDIxM3RuMDM4QHV0ZXouZWR1Lm14IiwiaWF0IjoxNjc4MjkxNzgyLCJleHAiOjE2NzgyOTM1ODJ9.pE2-Q9XWrO5InpVRy2e79c8w4H5_rMb8Oxnwp4Hq9_Q
Content-Type: application/json

{
  "name": "Course 1",
  "description": "Course 1 description",
  "discount": null,
  "price": 100.50,
  "image": "https://res.cloudinary.com/sigsa/image/upload/v1660851428/products/nvn3alt79ctkmdruafba.png",
  "category": {
        "id": 1
   }
}

###
PUT http://localhost:8080/api/courses/1